### ISSUE TITLE
Setup local dev environment for Nvm Forked Node

### ISSUE THREAD

**Issue by fabriziogianni7** [keyko-io/botblock-mvp#74]
## Description

The goal of this ticket is to setup the local dev environment and deploy the node to either Goerli or Sepolia (Sepolia is preferred if possible).

## Acceptance criteria

- Node deployed or locally setup
- Connect to it from the front end
- Do some operation to validate its functionality

**Comment by juanmanso** [comment]
Deployment of the node is postponed, scoped to just local usage
